### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by Maadtin** [anishkny/playwright-test-coverage-demo#19]
Doesn't generate `coverage` folder and `test-results` is an empty folder after executing the `test` script and tests successfully passes.

**Comment by happykmm** [comment]
+1, I have the same issue

**Comment by anishkny** [comment]
`test-results` folder is expected to be empty since there are no screenshots or other artifacts generated during test run.

Unfortunately, I was not able to reproduce empty `coverage` folder locally or in CI (GH Actions). See archived artifact [here](https://github.com/anishkny/playwright-test-coverage-demo/actions/runs/6178362427).
